### PR TITLE
fix: add options from previous step in the fallback comment

### LINKED ISSUE #60: fix display quick replies on misunderstood comment

### PR DESCRIPTION
**Pull request by spaenleh**
closes #60

### CODE REVIEW

File: src/utils/autoBotEngine.js [hunk 1]
```diff
@@ -136,6 +140,16 @@ const getDefaultOptionText = (personality) => {
   };
 };
 
+const getStep = (personality, stepId) => {
+  let personalityObj = personality;
+  if (typeof personality === 'string') {
```
Comment (juancarlosfarah) [inline src/utils/autoBotEngine.js:145]: Use `_.isString` to take care of both string primitive and String object.

File: src/utils/autoBotEngine.js [hunk 2]
```diff
@@ -121,7 +121,11 @@ const getFallbackOptionText = (personality, id) => {
   }
   return `${
     personalityObj.fallback.text
-  }${DEFAULT_PERSONALITY_FALLBACK_SEPARATOR}${getFormattedOptionText(step)}`;
+  }${DEFAULT_PERSONALITY_FALLBACK_SEPARATOR}${getFormattedOptionText(
+    step,
+  )}${DEFAULT_PERSONALITY_FALLBACK_SEPARATOR}You can reply with "${step.options.join(
```
Comment (juancarlosfarah) [inline src/utils/autoBotEngine.js:126]: Can leave this for now, but maybe translate `You can reply with` and add a colon at the end`:`.

**Review by juancarlosfarah — CHANGES_REQUESTED** [review]
Looks good! Just some minor changes.
