### PR TITLE
fix: correct avatar bug and add upload list of users feature

### LINKED ISSUE #90: Fix Avatar settings
Avatar settings are behaving weirldy when using the "cancel" button.

Sometimes it will open the “new bot” dialog instead of the “edit bot” dialog if you exited with “Cancel” the previous time.

### PR DESCRIPTION
**Pull request by spaenleh**
This PR corrects the bug in avatar settings and adds the possibility of importing ids list to be set as the bot's `userList`.
Also the list can now be sorted by `name` or by `userId`.
New UI for the settings:
Screenshot 2022-04-27 at 14 58 50

A Toast appears if the file can not be processed correctly:
Screenshot 2022-04-27 at 14 59 04

closes #90

### CODE REVIEW

File: src/components/modes/teacher/AvatarDialog.js [hunk 1]
```diff
@@ -438,6 +475,16 @@ class AvatarDialog extends Component {
...
 
+    const sortedUsers = users.sort((a, b) => {
+      if (userSortByName) {
+        return a.name.localeCompare(b.name);
+      }
+      if (typeof a.id === 'string') {
+        return a.id.localeCompare(b.id);
+      }
+      return a.id - b.id;
+    });
```
Comment (juancarlosfarah) [inline src/components/modes/teacher/AvatarDialog.js:486]: Can you not use `lodash`?

File: src/components/modes/teacher/AvatarDialog.js [hunk 2]
```diff
@@ -769,6 +855,15 @@ class AvatarDialog extends Component {
         >
           {t('Cancel')}
         </Button>
+        <Snackbar
+          open={snackOpen}
+          autoHideDuration={6000}
```
Comment (juancarlosfarah) [inline src/components/modes/teacher/AvatarDialog.js:860]: Factor this out to the settings file.

File: src/components/modes/teacher/AvatarDialog.js (hunk 1 above)
Comment (juancarlosfarah) [inline src/components/modes/teacher/AvatarDialog.js:486]: Maybe comment the different cases here. for clarity?

Comment (juancarlosfarah) [reply src/components/modes/teacher/AvatarDialog.js:486]: Ignore this comment.

**Review by juancarlosfarah — CHANGES_REQUESTED** [review]
Looks good! Just some minor changes.
